# custom-metrics
---
apiVersion: autoscaling/v2alpha1
kind: HorizontalPodAutoscaler
metadata:
  name: example-app
  namespace: default
spec:
  scaleTargetRef:
    #apiVersion: apps/v1beta1
    kind: Deployment
    name: example-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Object
    object:
      metricName: go_goroutines
      target:
        apiVersion: extensions/v1beta1
        kind: Deployment
        name: example-app
      targetValue: 10k
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: custom-metrics-apiserver
  namespace: default
  labels:
    app: custom-metrics-apiserver
spec:
  replicas: 1
  template:
    metadata:
      name: custom-metrics-apiserver
      labels:
        app: custom-metrics-apiserver
    spec:
      containers:
      - name: custom-metrics-server
        image: luxas/custom-metrics-server:v0.2.1
        args:
        - --prometheus-endpoint=http://prometheus-frontend.default.svc:9090
        - --authentication-skip-lookup=true
        ports:
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: default
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: custom-metrics-apiserver
---
apiVersion: apiregistration.k8s.io/v1alpha1
kind: APIService
metadata:
  name: v1alpha1.custom-metrics.metrics.k8s.io
spec:
  insecureSkipTLSVerify: true
  group: custom-metrics.metrics.k8s.io
  priority: 150
  service:
    name: api
    namespace: default
  version: v1alpha1
