# ---
# kind: Namespace
# apiVersion: v1
# metadata:
#   name: custom-metrics
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: prom
  labels:
    name: prom
spec:
  replicas: 2
  selector:
    name: prom
  template:
    metadata:
      labels:
        name: prom
    spec:
      containers:
      - name: prom
        image: prom/prometheus:v1.4.1
        ports:
        - name: prometheus
          containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prom
  labels:
    name: prom
spec:
  type: LoadBalancer
  ports:
  - name: prometheus
    port: 9090
    targetPort: 9090
  selector:
    name: prom
---
apiVersion: autoscaling/v2alpha1
kind: HorizontalPodAutoscaler
metadata:
  name: prom
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: ReplicationController
    name: prom
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Object
    object:
      metricName: go_goroutines
      target:
        apiVersion: extensions/v1beta1
        kind: Service
        name: prom
      targetValue: 10k
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: custom-metrics-apiserver
  namespace: custom-metrics
  labels:
    app: custom-metrics-apiserver
spec:
  replicas: 1
  template:
    metadata:
      name: custom-metrics-apiserver
      labels:
        app: custom-metrics-apiserver
    spec:
      tolerations:
      - key: beta.kubernetes.io/arch
        value: arm
        effect: NoSchedule
      - key: beta.kubernetes.io/arch
        value: arm64
        effect: NoSchedule
      containers:
      - name: custom-metrics-server
        image: luxas/custom-metrics-server:v0.2.1
        args:
        - --prometheus-endpoint=http://prom.default.svc:9090
        - --authentication-skip-lookup=true
        ports:
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: custom-metrics
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: custom-metrics-apiserver
---
apiVersion: apiregistration.k8s.io/v1alpha1
kind: APIService
metadata:
  name: v1alpha1.custom-metrics.metrics.k8s.io
spec:
  insecureSkipTLSVerify: true
  group: custom-metrics.metrics.k8s.io
  priority: 150
  service:
    name: api
    namespace: custom-metrics
  version: v1alpha1
# ---
# kind: Namespace
# apiVersion: v1
# metadata:
#   name: wardle
# ---
# apiVersion: apiregistration.k8s.io/v1alpha1
# kind: APIService
# metadata:
#   name: v1alpha1.wardle.k8s.io
# spec:
#   insecureSkipTLSVerify: true
#   group: wardle.k8s.io
#   priority: 200
#   service:
#     name: api
#     namespace: wardle
#   version: v1alpha1
# ---
# apiVersion: v1
# kind: ReplicationController
# metadata:
#   name: wardle-server
#   namespace: wardle
#   labels:
#     apiserver: "true"
# spec:
#   replicas: 1
#   selector:
#     apiserver: "true"
#   template:
#     metadata:
#       labels:
#         apiserver: "true"
#     spec:
#       containers:
#       - name: wardle-server
#         image: deshuai/kube-sample-apiserver:latest
#         # image: kube-sample-apiserver:latest
#         # imagePullPolicy: Never
#         args:
#         - "--etcd-servers=http://localhost:2379"
#         - "--authentication-skip-lookup=true"
#       - name: etcd
#         image: quay.io/coreos/etcd:v3.0.17
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: api
#   namespace: wardle
# spec:
#   ports:
#   - port: 443
#     protocol: TCP
#     targetPort: 443
#   selector:
#     apiserver: "true"
