routers:
- protocol: http
  servers:
  - port: 4141
    ip: 0.0.0.0
  baseDtab: |
    /srv => /$/inet/web/8080;
    /http/*/* => /srv;

- protocol: h2
  experimental: true
  label: grpc
  servers:
  - port: 4142
    ip: 0.0.0.0
  dstPrefix: /grpc
  identifier:
    kind: io.l5d.headerPath
  baseDtab: |
    /srv/proto.GenSvc   => /$/inet/gen/8181;
    /srv/proto.WordSvc  => /$/inet/word/8282;
    /grpc => /srv;
