admin:
  port: 9990

namers:
- kind: io.l5d.marathon
  host: marathon.mesos
  port: 8080
  prefix: "/io.l5d.marathon"
  experimental: true

routers:
- protocol: http
  servers:
  - port: 4140
    ip: 0.0.0.0
  baseDtab: "/http/1.1/*=>/#/io.l5d.marathon"
  label: linkerd_proxy
