# linkerd config for basic http proxy
# listens on port 4140, routes via http_proxy or host header

admin:
  port: 9990

namers:
- kind: io.l5d.marathon
  host: marathon.mesos
  port: 8080
  experimental: true

routers:
- protocol: http
  servers:
  - port: 4140
    ip: 0.0.0.0
  baseDtab: >- # route based on marathon name
    /marathonId => /#/io.l5d.marathon;
    /http/1.1/* => /$/io.buoyant.http.domainToPathPfx/marathonId;
  label: linkerd_proxy
