# linkerd config for basic http proxy plus ingress
# port 4140 for normal internal requests
# port 4242 automatically routes to "webapp"

admin:
  port: 9990

namers:
- kind: io.l5d.marathon
  host: marathon.mesos
  port: 8080
  experimental: true

routers:
- protocol: http
  servers:
  - port: 4140
    ip: 0.0.0.0
  baseDtab: >- # route based on marathon name
    /marathonId => /#/io.l5d.marathon;
    /http/1.1/* => /$/io.buoyant.http.domainToPathPfx/marathonId;
  label: linkerd_proxy
- protocol: http
  servers:
  - port: 4242
    ip: 0.0.0.0
  baseDtab: >- # force all requests to `webapp`
    /http/*/*/* => /#/io.l5d.marathon/webapp;
  label: external
