# linkerd config for use with namerd
# all service discovery managed via namerd

admin:
  port: 9990

routers:
- protocol: http
  servers:
  - port: 4140
    ip: 0.0.0.0
  label: linkerd_proxy
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd.marathon.mesos/4100
